In [1]:
#importer les packages
import os
import pandas as pd
from tqdm.notebook import tqdm
tqdm.pandas()

from utils.correcting_features import corrige_all, corrige_etabli2, corrige_rgp2, corrige_rgp3, corrige_op_ing
from utils.load_corrections import get_all_correctifs_from_google, load_all_correctifs
from utils.traitements import importtab, gentab

In [2]:
# ATTENTION, avant de commencer, s'assurer d'avoir un dossier "INPUT" 
# avec les données au format parquet pour chaque année et un dossier
# POST_GENTAB pour acceuillir les données traitées (attention c'est assez volumineux)

# Modifier la page format du googlesheet si il y a de nouveaux formats cette année
# Modifier également la page D_EPE du googlesheet ESR pour ajouter les EPE de la nouvelle année

In [2]:
DATA_PATH=os.getcwd()

In [3]:
url_atlas='https://docs.google.com/spreadsheet/ccc?key=11NFXSIg6gQMCsMa8zWQQyypvvYBEmfyJfF2yytXqgMk&output=xls'
url_esr='https://docs.google.com/spreadsheet/ccc?key=1FwPq5Qw7Gbgj_sBD6Za4dfDDk6ydozQ99TyRjLkW5d8&output=xls'

VARS_atlas=['COM_U','COM_M', 'ETABLI', 'MINISTER', 'DC', 'NATION', 'ETABLI2', 'FORMAT','CURSUS_LMD', 'DISCIPLI','RGP2', 'RGP3','OP_ING','SECRET']
VARS_esr=['O_DUTBUT','J_LMDDONT','DISCIPLINES_SISE','FORMAT','LES_COMMUNES','D_EPE','C_ETABLISSEMENTS']

Charger les données des googlesheets depuis google en local au format .json dans le dossier (pas besoin de le faire à chaque fois, à faire si c'est la première fois OU lors d'une modification sur le.s googlesheet.s)

In [4]:
get_all_correctifs_from_google(url_atlas,VARS_atlas,'_atlas')
get_all_correctifs_from_google(url_esr,VARS_esr,'_esr')

Charger les 2 googlessheets dans le notebook

In [5]:
CORRECTIFS_dict_esr = load_all_correctifs('_esr')
CORRECTIFS_dict = load_all_correctifs('_atlas')

In [6]:
formats=pd.DataFrame(CORRECTIFS_dict_esr['FORMAT']).drop_duplicates()

On charge bien la rentrée scolaire de l'année en cours

In [7]:
rentree_sco=2024

On charge les données correspondantes

In [48]:
df2=pd.read_parquet(f"./INPUT/ts{str(rentree_sco)[2:]}d_tot.parquet", engine='fastparquet')

In [49]:
df=pd.read_parquet(f"./INPUT/ts{str(rentree_sco)[2:]}d_tot_ancien.parquet", engine='fastparquet')

In [145]:
df_diff = df_formats.merge(df2_formats, how='outer', indicator=True)
df_diff = df_diff[df_diff['_merge'] != 'both']

In [146]:
pd.DataFrame(df_diff.value_counts()).to_csv('diff.csv', sep=";")

In [150]:
l1=list(df_formats[~df_formats['FORMAT'].isin(df2_formats['FORMAT'])].ETABLI)

In [149]:
l2=list(df2_formats[~df2_formats['FORMAT'].isin(df_formats['FORMAT'])].ETABLI)

In [153]:
[x for x in l2 if x not in l1]

['9830445S', '9830445S']

In [143]:
df_formats=pd.DataFrame(df[['COMPOS','ETABLI','FORMAT','EFFTOT']].value_counts()).reset_index()

In [144]:
df2_formats=pd.DataFrame(df2[['COMPOS','ETABLI','FORMAT','EFFTOT']].value_counts()).reset_index()

In [ ]:
df.columns=[x.upper() for x in df.columns]

In [173]:
df2[df2.ETABLI.apply(lambda x: x=='0442427Z')].drop_duplicates([ 'ETABLI', 'COMPOS', 'NATR',
       'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE', 'DEGETU'])[[ 'ETABLI', 'COMPOS', 'NATR',
       'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE', 'DEGETU']]

           ETABLI    COMPOS NATR SEXE DISCIPLI CURSUS_LMD   AGE DEGETU
1913269  0442427Z  0442427Z    1    1       04          L  33.0      2
1913270  0442427Z  0442427Z    1    1       04          L  24.0      2
1913271  0442427Z  0442427Z    1    1       04          L  19.0      1
1913272  0442427Z  0442427Z    1    1       04          L  19.0      2
1913273  0442427Z  0442427Z    1    1       04          L  19.0      3
...           ...       ...  ...  ...      ...        ...   ...    ...
1956761  0442427Z  0442427Z    2    2       04          M  22.0      5
1957562  0442427Z  0442427Z    2    1       04          M  24.0      3
1957563  0442427Z  0442427Z    2    2       04          M  23.0      4
1960825  0442427Z  0442427Z    2    2       04          L  22.0      3
1961166  0442427Z  0442427Z    2    2       04          M  24.0      4

[82 rows x 8 columns]

In [182]:
df.loc[df.ETABLI.apply(lambda x: x=='0442427Z') & pd.isna(df.DEGETU)]

,SECTEUR,FORMAT,ENQ,NATION,ETABLI,COMPOS,NATR,SEXE,GROUPE,TYP_DIPL,...,CODE_STATUT_ETUDIANT,EFFECTIF_SANS_DOUBLE_COMPTE,MOB_DIPL,MOB_INTER,FR_ETR,MOB_DIPLBIS,POIDS_DIPL,MOB_INTERBIS,POIDS_INTER,OPERATEUR150
1954839,03,art,cult,131,0442427Z,0442427Z,2,1,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1955057,03,art,cult,132,0442427Z,0442427Z,2,1,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1956761,03,art,cult,205,0442427Z,0442427Z,2,2,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1957562,03,art,cult,216,0442427Z,0442427Z,2,1,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1957563,03,art,cult,216,0442427Z,0442427Z,2,2,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1961166,03,art,cult,333,0442427Z,0442427Z,2,2,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None

In [183]:
df2.loc[df2.ETABLI.apply(lambda x: x=='0442427Z') & pd.isna(df2.DEGETU)]

Empty DataFrame
Columns: [SECTEUR, FORMAT, ENQ, NATION, ETABLI, COMPOS, NATR, SEXE, GROUPE, TYP_DIPL, DISCIPLI, SECTDIS, DIPLOM, REGIME, CURSUS_LMD, UNIV, FLAG_MEEF, HCPGE, DBCOMPTE, BAC_RGRP, ACABAC, ANBAC, PCS, ETABLI_DIFFUSION, AGE, ECHANG, DEGETU, FLAG_REGROUPEMENT, IMPUTATION, INDIC_COMUE, OPPOS, COMUE_RATT, TYPE, ETABLI_RATT, MEFBCP11, MEFST11, HSIFA, DIPLOME_STSAP, FR_ETR_R, FR_ETR_D, ADRESSE, ADRESSE_UAI, CONTRAT, DENOMINATION_PRINCIPALE_UAI, DEP, DISC, FINECOLE, LIBELLE ROUTAGE, LOCALITE_ACHEMINEMENT_UAI, MINISTERE_TUTELLE, NIVEAU_UAI, NIVFORM, NOMECOLE, PATRONYME_UAI, NATIO, LIG, NIVEAU_U, TYPE_LIB, Z_COL1, Z_COL2, Z_COL3, Z_COL4, Z_COL5, Z_COL6, Z_COL7, Z_COL8, Z_COL9, Z_COL10, Z_COL11, Z_COL12, TAB02, TAB04, TAB05, TAB06, TAB07, TAB08, TAB09, TAB10, NEW_ETAB_ANC, NEW_ETAB_RENTREE, FRA, ETR, EFFTOT, EFFTOTN, EFFTOTA, ANNEE, CONTRAT_M, SIGLE_M, SECT_M, NAT_M, COM_M, LIB1_M, LIB2_M, ACA_M, MIN_M, CONTRAT_U, SIGLE_U, SECT_U, NAT_U, COM_U, ...]
Index: []

[0 rows x 118 columns]

In [186]:
df_complet = (
    pd.merge(df,
        df2[df2['ETABLI'] == '0442427Z']
        .drop_duplicates(['ETABLI', 'COMPOS', 'NATR', 'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE','DEGETU'])[['ETABLI', 'COMPOS', 'NATR', 'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE','DEGETU']],
        on=['ETABLI', 'COMPOS', 'NATR', 'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE'],
        how='left',
        suffixes=('', '_y')
    )
)

In [191]:
df_complet.loc[(df_complet['ETABLI'] == '0442427Z') & (df_complet['DEGETU'].isna())& (df_complet['DEGETU_y'].isna())][['ETABLI', 'COMPOS', 'NATR', 'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE','DEGETU']]

           ETABLI    COMPOS NATR SEXE DISCIPLI CURSUS_LMD   AGE DEGETU
1954942  0442427Z  0442427Z    2    1       04          M  23.0   None
1955160  0442427Z  0442427Z    2    1       04          M  20.0   None
1956864  0442427Z  0442427Z    2    2       04          M  21.0   None
1957665  0442427Z  0442427Z    2    1       04          M  23.0   None

In [197]:
df.loc[(df['ETABLI'] == '0442427Z') & (df['DEGETU'].isna())][['ETABLI', 'COMPOS', 'NATR', 'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE','DEGETU']]

           ETABLI    COMPOS NATR SEXE DISCIPLI CURSUS_LMD   AGE DEGETU
1954839  0442427Z  0442427Z    2    1       04          M  23.0   None
1955057  0442427Z  0442427Z    2    1       04          M  20.0   None
1956761  0442427Z  0442427Z    2    2       04          M  21.0   None
1957562  0442427Z  0442427Z    2    1       04          M  23.0   None
1957563  0442427Z  0442427Z    2    2       04          M  22.0   None
1961166  0442427Z  0442427Z    2    2       04          M  23.0   None

In [196]:
df2.loc[(df2['ETABLI'] == '0442427Z')&(df2['NATR'] == '2')&(df2['SEXE'] == '1')][['ETABLI', 'COMPOS', 'NATR', 'SEXE', 'DISCIPLI', 'CURSUS_LMD', 'AGE','DEGETU']]

           ETABLI    COMPOS NATR SEXE DISCIPLI CURSUS_LMD   AGE DEGETU
1954838  0442427Z  0442427Z    2    1       04          L  19.0      2
1954839  0442427Z  0442427Z    2    1       04          M  24.0      4
1955057  0442427Z  0442427Z    2    1       04          M  21.0      5
1957562  0442427Z  0442427Z    2    1       04          M  24.0      3

In [179]:
df_complet.loc[(df_complet['ETABLI'] == '0442427Z') & (df_complet['DEGETU'].isna()), 'DEGETU'] = df_complet.loc[(df_complet['ETABLI'] == '0442427Z') & (df_complet['DEGETU'].isna()), 'DEGETU_y']
#df_complet = df_complet.drop(columns='DEGETU_y')

In [181]:
df_complet.loc[(df_complet['ETABLI'] == '0442427Z') & (df_complet['DEGETU'].isna()), 'DEGETU']

1954942    NaN
1955160    NaN
1956864    NaN
1957665    NaN
Name: DEGETU, dtype: object

In [177]:
df_complet.loc[df_complet.ETABLI.apply(lambda x: x=='0442427Z') & pd.isna(df_complet.DEGETU)]

,SECTEUR,FORMAT,ENQ,NATION,ETABLI,COMPOS,NATR,SEXE,GROUPE,TYP_DIPL,...,CODE_STATUT_ETUDIANT,EFFECTIF_SANS_DOUBLE_COMPTE,MOB_DIPL,MOB_INTER,FR_ETR,MOB_DIPLBIS,POIDS_DIPL,MOB_INTERBIS,POIDS_INTER,OPERATEUR150
1954942,03,art,cult,131,0442427Z,0442427Z,2,1,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1955160,03,art,cult,132,0442427Z,0442427Z,2,1,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1956864,03,art,cult,205,0442427Z,0442427Z,2,2,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None
1957665,03,art,cult,216,0442427Z,0442427Z,2,1,3,11,...,SC,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,None

In [38]:
#verifier que HCPGE est bien rempli
if 'HCPGE' in list(df.columns):
    print(df.HCPGE.value_counts())

HCPGE
1.0    1355746
0.0      28309
Name: count, dtype: int64

In [39]:
#voir les effectifs sans les doubles comptes
if 'HSIFA' in list(df.columns):
    print(df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())
    print(df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

2896269.0
187500.0

On applique la fonction importtab, qui va corriger les features une par une de cette année

In [40]:
df_up=importtab(df,CORRECTIFS_dict,CORRECTIFS_dict_esr,corrige_etabli2,corrige_all,rentree_sco)

c:\Users\haallat\Documents\atlas-opendata\utils\traitements.py:51: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'DU' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df.loc[df['TYP_DIPL'].isin(["01","02","04","05","06","07","08","09","17","UA","UB","UC","UD","UE","UF","UG","UI","UJ","UO","UR","US","UT","UU","UV","UY","XF"]),'DNDU']='DU'

COM_U
COM_M
ETABLI
DISCIPLI
FORMAT
MINISTER
NATION
CURSUS_LMD
ETABLI2

In [41]:
# test EFFTOT si ils sont toujours egaux sans HSIFA
if 'HSIFA' in list(df.columns):
    print(df_up['HSIFA'].value_counts())
    print(df_up.EFFTOT.sum()-df_up.loc[(df_up['HSIFA']==0.0),'EFFTOT'].sum()==df.EFFTOT.sum()-df.loc[(df['HSIFA']==0.0),'EFFTOT'].sum())

HSIFA
0.0    120741
Name: count, dtype: int64
True

In [42]:
# test si nouveaux formats cette année
[x for x in list(df_up.FORMAT.drop_duplicates()) if x not in list(pd.DataFrame(CORRECTIFS_dict_esr['FORMAT'])['FORMAT'].drop_duplicates())]

[]

In [45]:
df_up

,FORMAT,ENQ,NATION,ETABLI,COMPOS,SEXE,DIPLOM,CURSUS_LMD,UNIV,HCPGE,...,EFFECTIF_SANS_DOUBLE_COMPTE,RENTREE,MINISTER,DNDU,DC,SPECIUT,LMDDONT,LMDDONTBIS,DISCIPLI,ETABLI2
0,espe,sise,100,0062205P,0062109K,1,2500248,M,O,1.0,...,1.0,2025,38,DN,1,AUTRES,MAS_M,MAS_ENS,LLSH,0062205P
1,espe,sise,100,0062205P,0062109K,1,2500248,M,O,1.0,...,1.0,2025,38,DN,1,AUTRES,MAS_M,MAS_ENS,LLSH,0062205P
2,espe,sise,100,0062205P,0062109K,1,2500248,M,O,1.0,...,1.0,2025,38,DN,1,AUTRES,MAS_M,MAS_ENS,LLSH,0062205P
3,espe,sise,100,0062205P,0062109K,1,2500248,M,O,1.0,...,1.0,2025,38,DN,1,AUTRES,MAS_M,MAS_ENS,LLSH,0062205P
4,espe,sise,100,0062205P,0062109K,1,2500248,M,O,1.0,...,1.0,2025,38,DN,1,AUTRES,MAS_M,MAS_ENS,LLSH,0062205P
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2215138,autr,jur,999,9741926A,9741926A,2,None,None,None,NaN,...,1.0,2025,38,DN,1,AUTRES,AUTRES,AUTRES,AUTRES,9741926A
2215139,autr,jur,999,9741926A,9741926A,1,None,None,None,NaN,...,1.0,2025,38,DN,1,AUTRES,AUTRES,AUTRES,AUTRES,9741926A
2215140,autr,jur,999,9741926A,9741926A,1,None,None,None,NaN,...,1.0,2025,38,DN,1,AUTRES,AUTRES,AUTRES,AUTRES,9741926A
2215141,co23,jur,999,0422297U,0422297U,1,None,None,None,NaN,...,1.0,2025,38,DN,1,AUTRES,AUTRES,AUTRES,AUTRES,0422297U
2215142,co23,jur,999,0422297U,0422297U,2,None,None,None,NaN,...,1.0,2025,38,DN,1,AUTRES,AUTRES,AUTRES,AUTRES,0422297U

In [15]:
#fonction gentab

In [ ]:
df_up2= gentab(df_up, rentree_sco, CORRECTIFS_dict, CORRECTIFS_dict_esr, corrige_rgp2, corrige_rgp3, corrige_op_ing)

On regarde si les effectifs des apprentis sont présents

In [ ]:
if 'EFF_STS_APP' in df_up2.columns:
    print(df_up2.EFF_STS_APP.value_counts())

Pour chaque année, on enregistre les données traitées

In [18]:
df_up2.to_json(f"./POST_GENTAB/atlas{str(rentree_sco)}.json")